/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiCeoRouteImport } from './routes/ai-ceo'
import { Route as OwnerRouteImport } from './routes/owner'
import { Route as SoftwarewalaRouteImport } from './routes/softwarewala'
import { Route as AiCeoIndexRouteImport } from './routes/ai-ceo.index'
import { Route as AiCeoActivityRouteImport } from './routes/ai-ceo.activity'
import { Route as AiCeoLiveMonitorRouteImport } from './routes/ai-ceo.live-monitor'
import { Route as AiCeoSettingsRouteImport } from './routes/ai-ceo.settings'
import { Route as ApiCeoBriefRouteImport } from './routes/api/ceo-brief'
import { Route as AiCeoAgentsIndexRouteImport } from './routes/ai-ceo.agents.index'
import { Route as AiCeoAgentsAgentIdRouteImport } from './routes/ai-ceo.agents.$agentId'
import { Route as AiCeoApprovalsIndexRouteImport } from './routes/ai-ceo.approvals.index'
import { Route as AiCeoApprovalsIdRouteImport } from './routes/ai-ceo.approvals.$id'
import { Route as AiCeoAutomationsIndexRouteImport } from './routes/ai-ceo.automations.index'
import { Route as AiCeoAutomationsAutomationIdRouteImport } from './routes/ai-ceo.automations.$automationId'
import { Route as AiCeoChatIndexRouteImport } from './routes/ai-ceo.chat.index'
import { Route as AiCeoChatThreadIdRouteImport } from './routes/ai-ceo.chat.$threadId'
import { Route as AiCeoCompanyBrainIndexRouteImport } from './routes/ai-ceo.company-brain.index'
import { Route as AiCeoCompanyBrainIdRouteImport } from './routes/ai-ceo.company-brain.$id'
import { Route as AiCeoDecisionEngineIndexRouteImport } from './routes/ai-ceo.decision-engine.index'
import { Route as AiCeoDecisionEngineIdRouteImport } from './routes/ai-ceo.decision-engine.$id'
import { Route as AiCeoLearningIndexRouteImport } from './routes/ai-ceo.learning.index'
import { Route as AiCeoLearningIdRouteImport } from './routes/ai-ceo.learning.$id'
import { Route as AiCeoPerformanceIndexRouteImport } from './routes/ai-ceo.performance.index'
import { Route as AiCeoPerformanceKpiRouteImport } from './routes/ai-ceo.performance.$kpi'
import { Route as AiCeoPredictionsIndexRouteImport } from './routes/ai-ceo.predictions.index'
import { Route as AiCeoPredictionsIdRouteImport } from './routes/ai-ceo.predictions.$id'
import { Route as AiCeoPredictionsScenariosRouteImport } from './routes/ai-ceo.predictions.scenarios'
import { Route as AiCeoProjectsIndexRouteImport } from './routes/ai-ceo.projects.index'
import { Route as AiCeoProjectsProjectIdRouteImport } from './routes/ai-ceo.projects.$projectId'
import { Route as AiCeoReportsIndexRouteImport } from './routes/ai-ceo.reports.index'
import { Route as AiCeoReportsIdRouteImport } from './routes/ai-ceo.reports.$id'
import { Route as AiCeoResearchIndexRouteImport } from './routes/ai-ceo.research.index'
import { Route as AiCeoResearchResearchIdRouteImport } from './routes/ai-ceo.research.$researchId'
import { Route as AiCeoRiskIndexRouteImport } from './routes/ai-ceo.risk.index'
import { Route as AiCeoRiskIdRouteImport } from './routes/ai-ceo.risk.$id'
import { Route as AiCeoTasksIndexRouteImport } from './routes/ai-ceo.tasks.index'
import { Route as AiCeoTasksTaskIdRouteImport } from './routes/ai-ceo.tasks.$taskId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiCeoRoute = AiCeoRouteImport.update({
  id: '/ai-ceo',
  path: '/ai-ceo',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRoute = OwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const SoftwarewalaRoute = SoftwarewalaRouteImport.update({
  id: '/softwarewala',
  path: '/softwarewala',
  getParentRoute: () => rootRouteImport,
} as any)
const AiCeoIndexRoute = AiCeoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AiCeoRoute,
} as any)
const AiCeoActivityRoute = AiCeoActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AiCeoRoute,
} as any)
const AiCeoLiveMonitorRoute = AiCeoLiveMonitorRouteImport.update({
  id: '/live-monitor',
  path: '/live-monitor',
  getParentRoute: () => AiCeoRoute,
} as any)
const AiCeoSettingsRoute = AiCeoSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AiCeoRoute,
} as any)
const ApiCeoBriefRoute = ApiCeoBriefRouteImport.update({
  id: '/api/ceo-brief',
  path: '/api/ceo-brief',
  getParentRoute: () => rootRouteImport,
} as any)
const AiCeoAgentsIndexRoute = AiCeoAgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => AiCeoRoute,
} as any)
const AiCeoAgentsAgentIdRoute = AiCeoAgentsAgentIdRouteImport.update({
  id: '/agents/$agentId',
  path: '/agents/$agentId',
  getParentRoute: () => AiCeoRoute,
} as any)
const AiCeoApprovalsIndexRoute = AiCeoApprovalsIndexRouteImport.update({
  id: '/approvals/',
  path: '/approvals/',
  getParentRoute: () => AiCeoRoute,
} as any)
const AiCeoApprovalsIdRoute = AiCeoApprovalsIdRouteImport.update({
  id: '/approvals/$id',
  path: '/approvals/$id',
  getParentRoute: () => AiCeoRoute,
} as any)
const AiCeoAutomationsIndexRoute = AiCeoAutomationsIndexRouteImport.update({
  id: '/automations/',
  path: '/automations/',
  getParentRoute: () => AiCeoRoute,
} as any)
const AiCeoAutomationsAutomationIdRoute =
  AiCeoAutomationsAutomationIdRouteImport.update({
    id: '/automations/$automationId',
    path: '/automations/$automationId',
    getParentRoute: () => AiCeoRoute,
  } as any)
const AiCeoChatIndexRoute = AiCeoChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => AiCeoRoute,
} as any)
const AiCeoChatThreadIdRoute = AiCeoChatThreadIdRouteImport.update({
  id: '/chat/$threadId',
  path: '/chat/$threadId',
  getParentRoute: () => AiCeoRoute,
} as any)
const AiCeoCompanyBrainIndexRoute = AiCeoCompanyBrainIndexRouteImport.update({
  id: '/company-brain/',
  path: '/company-brain/',
  getParentRoute: () => AiCeoRoute,
} as any)
const AiCeoCompanyBrainIdRoute = AiCeoCompanyBrainIdRouteImport.update({
  id: '/company-brain/$id',
  path: '/company-brain/$id',
  getParentRoute: () => AiCeoRoute,
} as any)
const AiCeoDecisionEngineIndexRoute =
  AiCeoDecisionEngineIndexRouteImport.update({
    id: '/decision-engine/',
    path: '/decision-engine/',
    getParentRoute: () => AiCeoRoute,
  } as any)
const AiCeoDecisionEngineIdRoute = AiCeoDecisionEngineIdRouteImport.update({
  id: '/decision-engine/$id',
  path: '/decision-engine/$id',
  getParentRoute: () => AiCeoRoute,
} as any)
const AiCeoLearningIndexRoute = AiCeoLearningIndexRouteImport.update({
  id: '/learning/',
  path: '/learning/',
  getParentRoute: () => AiCeoRoute,
} as any)
const AiCeoLearningIdRoute = AiCeoLearningIdRouteImport.update({
  id: '/learning/$id',
  path: '/learning/$id',
  getParentRoute: () => AiCeoRoute,
} as any)
const AiCeoPerformanceIndexRoute = AiCeoPerformanceIndexRouteImport.update({
  id: '/performance/',
  path: '/performance/',
  getParentRoute: () => AiCeoRoute,
} as any)
const AiCeoPerformanceKpiRoute = AiCeoPerformanceKpiRouteImport.update({
  id: '/performance/$kpi',
  path: '/performance/$kpi',
  getParentRoute: () => AiCeoRoute,
} as any)
const AiCeoPredictionsIndexRoute = AiCeoPredictionsIndexRouteImport.update({
  id: '/predictions/',
  path: '/predictions/',
  getParentRoute: () => AiCeoRoute,
} as any)
const AiCeoPredictionsIdRoute = AiCeoPredictionsIdRouteImport.update({
  id: '/predictions/$id',
  path: '/predictions/$id',
  getParentRoute: () => AiCeoRoute,
} as any)
const AiCeoPredictionsScenariosRoute =
  AiCeoPredictionsScenariosRouteImport.update({
    id: '/predictions/scenarios',
    path: '/predictions/scenarios',
    getParentRoute: () => AiCeoRoute,
  } as any)
const AiCeoProjectsIndexRoute = AiCeoProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AiCeoRoute,
} as any)
const AiCeoProjectsProjectIdRoute = AiCeoProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => AiCeoRoute,
} as any)
const AiCeoReportsIndexRoute = AiCeoReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => AiCeoRoute,
} as any)
const AiCeoReportsIdRoute = AiCeoReportsIdRouteImport.update({
  id: '/reports/$id',
  path: '/reports/$id',
  getParentRoute: () => AiCeoRoute,
} as any)
const AiCeoResearchIndexRoute = AiCeoResearchIndexRouteImport.update({
  id: '/research/',
  path: '/research/',
  getParentRoute: () => AiCeoRoute,
} as any)
const AiCeoResearchResearchIdRoute = AiCeoResearchResearchIdRouteImport.update({
  id: '/research/$researchId',
  path: '/research/$researchId',
  getParentRoute: () => AiCeoRoute,
} as any)
const AiCeoRiskIndexRoute = AiCeoRiskIndexRouteImport.update({
  id: '/risk/',
  path: '/risk/',
  getParentRoute: () => AiCeoRoute,
} as any)
const AiCeoRiskIdRoute = AiCeoRiskIdRouteImport.update({
  id: '/risk/$id',
  path: '/risk/$id',
  getParentRoute: () => AiCeoRoute,
} as any)
const AiCeoTasksIndexRoute = AiCeoTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AiCeoRoute,
} as any)
const AiCeoTasksTaskIdRoute = AiCeoTasksTaskIdRouteImport.update({
  id: '/tasks/$taskId',
  path: '/tasks/$taskId',
  getParentRoute: () => AiCeoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-ceo': typeof AiCeoRouteWithChildren
  '/owner': typeof OwnerRoute
  '/softwarewala': typeof SoftwarewalaRoute
  '/ai-ceo/activity': typeof AiCeoActivityRoute
  '/ai-ceo/live-monitor': typeof AiCeoLiveMonitorRoute
  '/ai-ceo/settings': typeof AiCeoSettingsRoute
  '/api/ceo-brief': typeof ApiCeoBriefRoute
  '/ai-ceo/': typeof AiCeoIndexRoute
  '/ai-ceo/agents/$agentId': typeof AiCeoAgentsAgentIdRoute
  '/ai-ceo/approvals/$id': typeof AiCeoApprovalsIdRoute
  '/ai-ceo/automations/$automationId': typeof AiCeoAutomationsAutomationIdRoute
  '/ai-ceo/chat/$threadId': typeof AiCeoChatThreadIdRoute
  '/ai-ceo/company-brain/$id': typeof AiCeoCompanyBrainIdRoute
  '/ai-ceo/decision-engine/$id': typeof AiCeoDecisionEngineIdRoute
  '/ai-ceo/learning/$id': typeof AiCeoLearningIdRoute
  '/ai-ceo/performance/$kpi': typeof AiCeoPerformanceKpiRoute
  '/ai-ceo/predictions/$id': typeof AiCeoPredictionsIdRoute
  '/ai-ceo/predictions/scenarios': typeof AiCeoPredictionsScenariosRoute
  '/ai-ceo/projects/$projectId': typeof AiCeoProjectsProjectIdRoute
  '/ai-ceo/reports/$id': typeof AiCeoReportsIdRoute
  '/ai-ceo/research/$researchId': typeof AiCeoResearchResearchIdRoute
  '/ai-ceo/risk/$id': typeof AiCeoRiskIdRoute
  '/ai-ceo/tasks/$taskId': typeof AiCeoTasksTaskIdRoute
  '/ai-ceo/agents/': typeof AiCeoAgentsIndexRoute
  '/ai-ceo/approvals/': typeof AiCeoApprovalsIndexRoute
  '/ai-ceo/automations/': typeof AiCeoAutomationsIndexRoute
  '/ai-ceo/chat/': typeof AiCeoChatIndexRoute
  '/ai-ceo/company-brain/': typeof AiCeoCompanyBrainIndexRoute
  '/ai-ceo/decision-engine/': typeof AiCeoDecisionEngineIndexRoute
  '/ai-ceo/learning/': typeof AiCeoLearningIndexRoute
  '/ai-ceo/performance/': typeof AiCeoPerformanceIndexRoute
  '/ai-ceo/predictions/': typeof AiCeoPredictionsIndexRoute
  '/ai-ceo/projects/': typeof AiCeoProjectsIndexRoute
  '/ai-ceo/reports/': typeof AiCeoReportsIndexRoute
  '/ai-ceo/research/': typeof AiCeoResearchIndexRoute
  '/ai-ceo/risk/': typeof AiCeoRiskIndexRoute
  '/ai-ceo/tasks/': typeof AiCeoTasksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/owner': typeof OwnerRoute
  '/softwarewala': typeof SoftwarewalaRoute
  '/ai-ceo/activity': typeof AiCeoActivityRoute
  '/ai-ceo/live-monitor': typeof AiCeoLiveMonitorRoute
  '/ai-ceo/settings': typeof AiCeoSettingsRoute
  '/api/ceo-brief': typeof ApiCeoBriefRoute
  '/ai-ceo': typeof AiCeoIndexRoute
  '/ai-ceo/agents/$agentId': typeof AiCeoAgentsAgentIdRoute
  '/ai-ceo/approvals/$id': typeof AiCeoApprovalsIdRoute
  '/ai-ceo/automations/$automationId': typeof AiCeoAutomationsAutomationIdRoute
  '/ai-ceo/chat/$threadId': typeof AiCeoChatThreadIdRoute
  '/ai-ceo/company-brain/$id': typeof AiCeoCompanyBrainIdRoute
  '/ai-ceo/decision-engine/$id': typeof AiCeoDecisionEngineIdRoute
  '/ai-ceo/learning/$id': typeof AiCeoLearningIdRoute
  '/ai-ceo/performance/$kpi': typeof AiCeoPerformanceKpiRoute
  '/ai-ceo/predictions/$id': typeof AiCeoPredictionsIdRoute
  '/ai-ceo/predictions/scenarios': typeof AiCeoPredictionsScenariosRoute
  '/ai-ceo/projects/$projectId': typeof AiCeoProjectsProjectIdRoute
  '/ai-ceo/reports/$id': typeof AiCeoReportsIdRoute
  '/ai-ceo/research/$researchId': typeof AiCeoResearchResearchIdRoute
  '/ai-ceo/risk/$id': typeof AiCeoRiskIdRoute
  '/ai-ceo/tasks/$taskId': typeof AiCeoTasksTaskIdRoute
  '/ai-ceo/agents': typeof AiCeoAgentsIndexRoute
  '/ai-ceo/approvals': typeof AiCeoApprovalsIndexRoute
  '/ai-ceo/automations': typeof AiCeoAutomationsIndexRoute
  '/ai-ceo/chat': typeof AiCeoChatIndexRoute
  '/ai-ceo/company-brain': typeof AiCeoCompanyBrainIndexRoute
  '/ai-ceo/decision-engine': typeof AiCeoDecisionEngineIndexRoute
  '/ai-ceo/learning': typeof AiCeoLearningIndexRoute
  '/ai-ceo/performance': typeof AiCeoPerformanceIndexRoute
  '/ai-ceo/predictions': typeof AiCeoPredictionsIndexRoute
  '/ai-ceo/projects': typeof AiCeoProjectsIndexRoute
  '/ai-ceo/reports': typeof AiCeoReportsIndexRoute
  '/ai-ceo/research': typeof AiCeoResearchIndexRoute
  '/ai-ceo/risk': typeof AiCeoRiskIndexRoute
  '/ai-ceo/tasks': typeof AiCeoTasksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-ceo': typeof AiCeoRouteWithChildren
  '/owner': typeof OwnerRoute
  '/softwarewala': typeof SoftwarewalaRoute
  '/ai-ceo/activity': typeof AiCeoActivityRoute
  '/ai-ceo/live-monitor': typeof AiCeoLiveMonitorRoute
  '/ai-ceo/settings': typeof AiCeoSettingsRoute
  '/api/ceo-brief': typeof ApiCeoBriefRoute
  '/ai-ceo/': typeof AiCeoIndexRoute
  '/ai-ceo/agents/$agentId': typeof AiCeoAgentsAgentIdRoute
  '/ai-ceo/approvals/$id': typeof AiCeoApprovalsIdRoute
  '/ai-ceo/automations/$automationId': typeof AiCeoAutomationsAutomationIdRoute
  '/ai-ceo/chat/$threadId': typeof AiCeoChatThreadIdRoute
  '/ai-ceo/company-brain/$id': typeof AiCeoCompanyBrainIdRoute
  '/ai-ceo/decision-engine/$id': typeof AiCeoDecisionEngineIdRoute
  '/ai-ceo/learning/$id': typeof AiCeoLearningIdRoute
  '/ai-ceo/performance/$kpi': typeof AiCeoPerformanceKpiRoute
  '/ai-ceo/predictions/$id': typeof AiCeoPredictionsIdRoute
  '/ai-ceo/predictions/scenarios': typeof AiCeoPredictionsScenariosRoute
  '/ai-ceo/projects/$projectId': typeof AiCeoProjectsProjectIdRoute
  '/ai-ceo/reports/$id': typeof AiCeoReportsIdRoute
  '/ai-ceo/research/$researchId': typeof AiCeoResearchResearchIdRoute
  '/ai-ceo/risk/$id': typeof AiCeoRiskIdRoute
  '/ai-ceo/tasks/$taskId': typeof AiCeoTasksTaskIdRoute
  '/ai-ceo/agents/': typeof AiCeoAgentsIndexRoute
  '/ai-ceo/approvals/': typeof AiCeoApprovalsIndexRoute
  '/ai-ceo/automations/': typeof AiCeoAutomationsIndexRoute
  '/ai-ceo/chat/': typeof AiCeoChatIndexRoute
  '/ai-ceo/company-brain/': typeof AiCeoCompanyBrainIndexRoute
  '/ai-ceo/decision-engine/': typeof AiCeoDecisionEngineIndexRoute
  '/ai-ceo/learning/': typeof AiCeoLearningIndexRoute
  '/ai-ceo/performance/': typeof AiCeoPerformanceIndexRoute
  '/ai-ceo/predictions/': typeof AiCeoPredictionsIndexRoute
  '/ai-ceo/projects/': typeof AiCeoProjectsIndexRoute
  '/ai-ceo/reports/': typeof AiCeoReportsIndexRoute
  '/ai-ceo/research/': typeof AiCeoResearchIndexRoute
  '/ai-ceo/risk/': typeof AiCeoRiskIndexRoute
  '/ai-ceo/tasks/': typeof AiCeoTasksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-ceo'
    | '/owner'
    | '/softwarewala'
    | '/ai-ceo/activity'
    | '/ai-ceo/live-monitor'
    | '/ai-ceo/settings'
    | '/api/ceo-brief'
    | '/ai-ceo/'
    | '/ai-ceo/agents/$agentId'
    | '/ai-ceo/approvals/$id'
    | '/ai-ceo/automations/$automationId'
    | '/ai-ceo/chat/$threadId'
    | '/ai-ceo/company-brain/$id'
    | '/ai-ceo/decision-engine/$id'
    | '/ai-ceo/learning/$id'
    | '/ai-ceo/performance/$kpi'
    | '/ai-ceo/predictions/$id'
    | '/ai-ceo/predictions/scenarios'
    | '/ai-ceo/projects/$projectId'
    | '/ai-ceo/reports/$id'
    | '/ai-ceo/research/$researchId'
    | '/ai-ceo/risk/$id'
    | '/ai-ceo/tasks/$taskId'
    | '/ai-ceo/agents/'
    | '/ai-ceo/approvals/'
    | '/ai-ceo/automations/'
    | '/ai-ceo/chat/'
    | '/ai-ceo/company-brain/'
    | '/ai-ceo/decision-engine/'
    | '/ai-ceo/learning/'
    | '/ai-ceo/performance/'
    | '/ai-ceo/predictions/'
    | '/ai-ceo/projects/'
    | '/ai-ceo/reports/'
    | '/ai-ceo/research/'
    | '/ai-ceo/risk/'
    | '/ai-ceo/tasks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/owner'
    | '/softwarewala'
    | '/ai-ceo/activity'
    | '/ai-ceo/live-monitor'
    | '/ai-ceo/settings'
    | '/api/ceo-brief'
    | '/ai-ceo'
    | '/ai-ceo/agents/$agentId'
    | '/ai-ceo/approvals/$id'
    | '/ai-ceo/automations/$automationId'
    | '/ai-ceo/chat/$threadId'
    | '/ai-ceo/company-brain/$id'
    | '/ai-ceo/decision-engine/$id'
    | '/ai-ceo/learning/$id'
    | '/ai-ceo/performance/$kpi'
    | '/ai-ceo/predictions/$id'
    | '/ai-ceo/predictions/scenarios'
    | '/ai-ceo/projects/$projectId'
    | '/ai-ceo/reports/$id'
    | '/ai-ceo/research/$researchId'
    | '/ai-ceo/risk/$id'
    | '/ai-ceo/tasks/$taskId'
    | '/ai-ceo/agents'
    | '/ai-ceo/approvals'
    | '/ai-ceo/automations'
    | '/ai-ceo/chat'
    | '/ai-ceo/company-brain'
    | '/ai-ceo/decision-engine'
    | '/ai-ceo/learning'
    | '/ai-ceo/performance'
    | '/ai-ceo/predictions'
    | '/ai-ceo/projects'
    | '/ai-ceo/reports'
    | '/ai-ceo/research'
    | '/ai-ceo/risk'
    | '/ai-ceo/tasks'
  id:
    | '__root__'
    | '/'
    | '/ai-ceo'
    | '/owner'
    | '/softwarewala'
    | '/ai-ceo/activity'
    | '/ai-ceo/live-monitor'
    | '/ai-ceo/settings'
    | '/api/ceo-brief'
    | '/ai-ceo/'
    | '/ai-ceo/agents/$agentId'
    | '/ai-ceo/approvals/$id'
    | '/ai-ceo/automations/$automationId'
    | '/ai-ceo/chat/$threadId'
    | '/ai-ceo/company-brain/$id'
    | '/ai-ceo/decision-engine/$id'
    | '/ai-ceo/learning/$id'
    | '/ai-ceo/performance/$kpi'
    | '/ai-ceo/predictions/$id'
    | '/ai-ceo/predictions/scenarios'
    | '/ai-ceo/projects/$projectId'
    | '/ai-ceo/reports/$id'
    | '/ai-ceo/research/$researchId'
    | '/ai-ceo/risk/$id'
    | '/ai-ceo/tasks/$taskId'
    | '/ai-ceo/agents/'
    | '/ai-ceo/approvals/'
    | '/ai-ceo/automations/'
    | '/ai-ceo/chat/'
    | '/ai-ceo/company-brain/'
    | '/ai-ceo/decision-engine/'
    | '/ai-ceo/learning/'
    | '/ai-ceo/performance/'
    | '/ai-ceo/predictions/'
    | '/ai-ceo/projects/'
    | '/ai-ceo/reports/'
    | '/ai-ceo/research/'
    | '/ai-ceo/risk/'
    | '/ai-ceo/tasks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiCeoRoute: typeof AiCeoRouteWithChildren
  OwnerRoute: typeof OwnerRoute
  SoftwarewalaRoute: typeof SoftwarewalaRoute
  ApiCeoBriefRoute: typeof ApiCeoBriefRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-ceo': {
      id: '/ai-ceo'
      path: '/ai-ceo'
      fullPath: '/ai-ceo'
      preLoaderRoute: typeof AiCeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner': {
      id: '/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof OwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/softwarewala': {
      id: '/softwarewala'
      path: '/softwarewala'
      fullPath: '/softwarewala'
      preLoaderRoute: typeof SoftwarewalaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-ceo/': {
      id: '/ai-ceo/'
      path: '/'
      fullPath: '/ai-ceo/'
      preLoaderRoute: typeof AiCeoIndexRouteImport
      parentRoute: typeof AiCeoRoute
    }
    '/ai-ceo/activity': {
      id: '/ai-ceo/activity'
      path: '/activity'
      fullPath: '/ai-ceo/activity'
      preLoaderRoute: typeof AiCeoActivityRouteImport
      parentRoute: typeof AiCeoRoute
    }
    '/ai-ceo/live-monitor': {
      id: '/ai-ceo/live-monitor'
      path: '/live-monitor'
      fullPath: '/ai-ceo/live-monitor'
      preLoaderRoute: typeof AiCeoLiveMonitorRouteImport
      parentRoute: typeof AiCeoRoute
    }
    '/ai-ceo/settings': {
      id: '/ai-ceo/settings'
      path: '/settings'
      fullPath: '/ai-ceo/settings'
      preLoaderRoute: typeof AiCeoSettingsRouteImport
      parentRoute: typeof AiCeoRoute
    }
    '/api/ceo-brief': {
      id: '/api/ceo-brief'
      path: '/api/ceo-brief'
      fullPath: '/api/ceo-brief'
      preLoaderRoute: typeof ApiCeoBriefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-ceo/agents/': {
      id: '/ai-ceo/agents/'
      path: '/agents'
      fullPath: '/ai-ceo/agents/'
      preLoaderRoute: typeof AiCeoAgentsIndexRouteImport
      parentRoute: typeof AiCeoRoute
    }
    '/ai-ceo/agents/$agentId': {
      id: '/ai-ceo/agents/$agentId'
      path: '/agents/$agentId'
      fullPath: '/ai-ceo/agents/$agentId'
      preLoaderRoute: typeof AiCeoAgentsAgentIdRouteImport
      parentRoute: typeof AiCeoRoute
    }
    '/ai-ceo/approvals/': {
      id: '/ai-ceo/approvals/'
      path: '/approvals'
      fullPath: '/ai-ceo/approvals/'
      preLoaderRoute: typeof AiCeoApprovalsIndexRouteImport
      parentRoute: typeof AiCeoRoute
    }
    '/ai-ceo/approvals/$id': {
      id: '/ai-ceo/approvals/$id'
      path: '/approvals/$id'
      fullPath: '/ai-ceo/approvals/$id'
      preLoaderRoute: typeof AiCeoApprovalsIdRouteImport
      parentRoute: typeof AiCeoRoute
    }
    '/ai-ceo/automations/': {
      id: '/ai-ceo/automations/'
      path: '/automations'
      fullPath: '/ai-ceo/automations/'
      preLoaderRoute: typeof AiCeoAutomationsIndexRouteImport
      parentRoute: typeof AiCeoRoute
    }
    '/ai-ceo/automations/$automationId': {
      id: '/ai-ceo/automations/$automationId'
      path: '/automations/$automationId'
      fullPath: '/ai-ceo/automations/$automationId'
      preLoaderRoute: typeof AiCeoAutomationsAutomationIdRouteImport
      parentRoute: typeof AiCeoRoute
    }
    '/ai-ceo/chat/': {
      id: '/ai-ceo/chat/'
      path: '/chat'
      fullPath: '/ai-ceo/chat/'
      preLoaderRoute: typeof AiCeoChatIndexRouteImport
      parentRoute: typeof AiCeoRoute
    }
    '/ai-ceo/chat/$threadId': {
      id: '/ai-ceo/chat/$threadId'
      path: '/chat/$threadId'
      fullPath: '/ai-ceo/chat/$threadId'
      preLoaderRoute: typeof AiCeoChatThreadIdRouteImport
      parentRoute: typeof AiCeoRoute
    }
    '/ai-ceo/company-brain/': {
      id: '/ai-ceo/company-brain/'
      path: '/company-brain'
      fullPath: '/ai-ceo/company-brain/'
      preLoaderRoute: typeof AiCeoCompanyBrainIndexRouteImport
      parentRoute: typeof AiCeoRoute
    }
    '/ai-ceo/company-brain/$id': {
      id: '/ai-ceo/company-brain/$id'
      path: '/company-brain/$id'
      fullPath: '/ai-ceo/company-brain/$id'
      preLoaderRoute: typeof AiCeoCompanyBrainIdRouteImport
      parentRoute: typeof AiCeoRoute
    }
    '/ai-ceo/decision-engine/': {
      id: '/ai-ceo/decision-engine/'
      path: '/decision-engine'
      fullPath: '/ai-ceo/decision-engine/'
      preLoaderRoute: typeof AiCeoDecisionEngineIndexRouteImport
      parentRoute: typeof AiCeoRoute
    }
    '/ai-ceo/decision-engine/$id': {
      id: '/ai-ceo/decision-engine/$id'
      path: '/decision-engine/$id'
      fullPath: '/ai-ceo/decision-engine/$id'
      preLoaderRoute: typeof AiCeoDecisionEngineIdRouteImport
      parentRoute: typeof AiCeoRoute
    }
    '/ai-ceo/learning/': {
      id: '/ai-ceo/learning/'
      path: '/learning'
      fullPath: '/ai-ceo/learning/'
      preLoaderRoute: typeof AiCeoLearningIndexRouteImport
      parentRoute: typeof AiCeoRoute
    }
    '/ai-ceo/learning/$id': {
      id: '/ai-ceo/learning/$id'
      path: '/learning/$id'
      fullPath: '/ai-ceo/learning/$id'
      preLoaderRoute: typeof AiCeoLearningIdRouteImport
      parentRoute: typeof AiCeoRoute
    }
    '/ai-ceo/performance/': {
      id: '/ai-ceo/performance/'
      path: '/performance'
      fullPath: '/ai-ceo/performance/'
      preLoaderRoute: typeof AiCeoPerformanceIndexRouteImport
      parentRoute: typeof AiCeoRoute
    }
    '/ai-ceo/performance/$kpi': {
      id: '/ai-ceo/performance/$kpi'
      path: '/performance/$kpi'
      fullPath: '/ai-ceo/performance/$kpi'
      preLoaderRoute: typeof AiCeoPerformanceKpiRouteImport
      parentRoute: typeof AiCeoRoute
    }
    '/ai-ceo/predictions/': {
      id: '/ai-ceo/predictions/'
      path: '/predictions'
      fullPath: '/ai-ceo/predictions/'
      preLoaderRoute: typeof AiCeoPredictionsIndexRouteImport
      parentRoute: typeof AiCeoRoute
    }
    '/ai-ceo/predictions/$id': {
      id: '/ai-ceo/predictions/$id'
      path: '/predictions/$id'
      fullPath: '/ai-ceo/predictions/$id'
      preLoaderRoute: typeof AiCeoPredictionsIdRouteImport
      parentRoute: typeof AiCeoRoute
    }
    '/ai-ceo/predictions/scenarios': {
      id: '/ai-ceo/predictions/scenarios'
      path: '/predictions/scenarios'
      fullPath: '/ai-ceo/predictions/scenarios'
      preLoaderRoute: typeof AiCeoPredictionsScenariosRouteImport
      parentRoute: typeof AiCeoRoute
    }
    '/ai-ceo/projects/': {
      id: '/ai-ceo/projects/'
      path: '/projects'
      fullPath: '/ai-ceo/projects/'
      preLoaderRoute: typeof AiCeoProjectsIndexRouteImport
      parentRoute: typeof AiCeoRoute
    }
    '/ai-ceo/projects/$projectId': {
      id: '/ai-ceo/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/ai-ceo/projects/$projectId'
      preLoaderRoute: typeof AiCeoProjectsProjectIdRouteImport
      parentRoute: typeof AiCeoRoute
    }
    '/ai-ceo/reports/': {
      id: '/ai-ceo/reports/'
      path: '/reports'
      fullPath: '/ai-ceo/reports/'
      preLoaderRoute: typeof AiCeoReportsIndexRouteImport
      parentRoute: typeof AiCeoRoute
    }
    '/ai-ceo/reports/$id': {
      id: '/ai-ceo/reports/$id'
      path: '/reports/$id'
      fullPath: '/ai-ceo/reports/$id'
      preLoaderRoute: typeof AiCeoReportsIdRouteImport
      parentRoute: typeof AiCeoRoute
    }
    '/ai-ceo/research/': {
      id: '/ai-ceo/research/'
      path: '/research'
      fullPath: '/ai-ceo/research/'
      preLoaderRoute: typeof AiCeoResearchIndexRouteImport
      parentRoute: typeof AiCeoRoute
    }
    '/ai-ceo/research/$researchId': {
      id: '/ai-ceo/research/$researchId'
      path: '/research/$researchId'
      fullPath: '/ai-ceo/research/$researchId'
      preLoaderRoute: typeof AiCeoResearchResearchIdRouteImport
      parentRoute: typeof AiCeoRoute
    }
    '/ai-ceo/risk/': {
      id: '/ai-ceo/risk/'
      path: '/risk'
      fullPath: '/ai-ceo/risk/'
      preLoaderRoute: typeof AiCeoRiskIndexRouteImport
      parentRoute: typeof AiCeoRoute
    }
    '/ai-ceo/risk/$id': {
      id: '/ai-ceo/risk/$id'
      path: '/risk/$id'
      fullPath: '/ai-ceo/risk/$id'
      preLoaderRoute: typeof AiCeoRiskIdRouteImport
      parentRoute: typeof AiCeoRoute
    }
    '/ai-ceo/tasks/': {
      id: '/ai-ceo/tasks/'
      path: '/tasks'
      fullPath: '/ai-ceo/tasks/'
      preLoaderRoute: typeof AiCeoTasksIndexRouteImport
      parentRoute: typeof AiCeoRoute
    }
    '/ai-ceo/tasks/$taskId': {
      id: '/ai-ceo/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/ai-ceo/tasks/$taskId'
      preLoaderRoute: typeof AiCeoTasksTaskIdRouteImport
      parentRoute: typeof AiCeoRoute
    }
  }
}

interface AiCeoRouteChildren {
  AiCeoActivityRoute: typeof AiCeoActivityRoute
  AiCeoLiveMonitorRoute: typeof AiCeoLiveMonitorRoute
  AiCeoSettingsRoute: typeof AiCeoSettingsRoute
  AiCeoIndexRoute: typeof AiCeoIndexRoute
  AiCeoAgentsAgentIdRoute: typeof AiCeoAgentsAgentIdRoute
  AiCeoApprovalsIdRoute: typeof AiCeoApprovalsIdRoute
  AiCeoAutomationsAutomationIdRoute: typeof AiCeoAutomationsAutomationIdRoute
  AiCeoChatThreadIdRoute: typeof AiCeoChatThreadIdRoute
  AiCeoCompanyBrainIdRoute: typeof AiCeoCompanyBrainIdRoute
  AiCeoDecisionEngineIdRoute: typeof AiCeoDecisionEngineIdRoute
  AiCeoLearningIdRoute: typeof AiCeoLearningIdRoute
  AiCeoPerformanceKpiRoute: typeof AiCeoPerformanceKpiRoute
  AiCeoPredictionsIdRoute: typeof AiCeoPredictionsIdRoute
  AiCeoPredictionsScenariosRoute: typeof AiCeoPredictionsScenariosRoute
  AiCeoProjectsProjectIdRoute: typeof AiCeoProjectsProjectIdRoute
  AiCeoReportsIdRoute: typeof AiCeoReportsIdRoute
  AiCeoResearchResearchIdRoute: typeof AiCeoResearchResearchIdRoute
  AiCeoRiskIdRoute: typeof AiCeoRiskIdRoute
  AiCeoTasksTaskIdRoute: typeof AiCeoTasksTaskIdRoute
  AiCeoAgentsIndexRoute: typeof AiCeoAgentsIndexRoute
  AiCeoApprovalsIndexRoute: typeof AiCeoApprovalsIndexRoute
  AiCeoAutomationsIndexRoute: typeof AiCeoAutomationsIndexRoute
  AiCeoChatIndexRoute: typeof AiCeoChatIndexRoute
  AiCeoCompanyBrainIndexRoute: typeof AiCeoCompanyBrainIndexRoute
  AiCeoDecisionEngineIndexRoute: typeof AiCeoDecisionEngineIndexRoute
  AiCeoLearningIndexRoute: typeof AiCeoLearningIndexRoute
  AiCeoPerformanceIndexRoute: typeof AiCeoPerformanceIndexRoute
  AiCeoPredictionsIndexRoute: typeof AiCeoPredictionsIndexRoute
  AiCeoProjectsIndexRoute: typeof AiCeoProjectsIndexRoute
  AiCeoReportsIndexRoute: typeof AiCeoReportsIndexRoute
  AiCeoResearchIndexRoute: typeof AiCeoResearchIndexRoute
  AiCeoRiskIndexRoute: typeof AiCeoRiskIndexRoute
  AiCeoTasksIndexRoute: typeof AiCeoTasksIndexRoute
}

const AiCeoRouteChildren: AiCeoRouteChildren = {
  AiCeoActivityRoute: AiCeoActivityRoute,
  AiCeoLiveMonitorRoute: AiCeoLiveMonitorRoute,
  AiCeoSettingsRoute: AiCeoSettingsRoute,
  AiCeoIndexRoute: AiCeoIndexRoute,
  AiCeoAgentsAgentIdRoute: AiCeoAgentsAgentIdRoute,
  AiCeoApprovalsIdRoute: AiCeoApprovalsIdRoute,
  AiCeoAutomationsAutomationIdRoute: AiCeoAutomationsAutomationIdRoute,
  AiCeoChatThreadIdRoute: AiCeoChatThreadIdRoute,
  AiCeoCompanyBrainIdRoute: AiCeoCompanyBrainIdRoute,
  AiCeoDecisionEngineIdRoute: AiCeoDecisionEngineIdRoute,
  AiCeoLearningIdRoute: AiCeoLearningIdRoute,
  AiCeoPerformanceKpiRoute: AiCeoPerformanceKpiRoute,
  AiCeoPredictionsIdRoute: AiCeoPredictionsIdRoute,
  AiCeoPredictionsScenariosRoute: AiCeoPredictionsScenariosRoute,
  AiCeoProjectsProjectIdRoute: AiCeoProjectsProjectIdRoute,
  AiCeoReportsIdRoute: AiCeoReportsIdRoute,
  AiCeoResearchResearchIdRoute: AiCeoResearchResearchIdRoute,
  AiCeoRiskIdRoute: AiCeoRiskIdRoute,
  AiCeoTasksTaskIdRoute: AiCeoTasksTaskIdRoute,
  AiCeoAgentsIndexRoute: AiCeoAgentsIndexRoute,
  AiCeoApprovalsIndexRoute: AiCeoApprovalsIndexRoute,
  AiCeoAutomationsIndexRoute: AiCeoAutomationsIndexRoute,
  AiCeoChatIndexRoute: AiCeoChatIndexRoute,
  AiCeoCompanyBrainIndexRoute: AiCeoCompanyBrainIndexRoute,
  AiCeoDecisionEngineIndexRoute: AiCeoDecisionEngineIndexRoute,
  AiCeoLearningIndexRoute: AiCeoLearningIndexRoute,
  AiCeoPerformanceIndexRoute: AiCeoPerformanceIndexRoute,
  AiCeoPredictionsIndexRoute: AiCeoPredictionsIndexRoute,
  AiCeoProjectsIndexRoute: AiCeoProjectsIndexRoute,
  AiCeoReportsIndexRoute: AiCeoReportsIndexRoute,
  AiCeoResearchIndexRoute: AiCeoResearchIndexRoute,
  AiCeoRiskIndexRoute: AiCeoRiskIndexRoute,
  AiCeoTasksIndexRoute: AiCeoTasksIndexRoute,
}

const AiCeoRouteWithChildren = AiCeoRoute._addFileChildren(AiCeoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiCeoRoute: AiCeoRouteWithChildren,
  OwnerRoute: OwnerRoute,
  SoftwarewalaRoute: SoftwarewalaRoute,
  ApiCeoBriefRoute: ApiCeoBriefRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
