/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiCeoRouteImport } from './routes/ai-ceo'
import { Route as OwnerRouteImport } from './routes/owner'
import { Route as SoftwarewalaRouteImport } from './routes/softwarewala'
import { Route as AiCeoIndexRouteImport } from './routes/ai-ceo.index'
import { Route as AiCeoActivityRouteImport } from './routes/ai-ceo.activity'
import { Route as AiCeoAgentsRouteImport } from './routes/ai-ceo.agents'
import { Route as AiCeoApprovalsRouteImport } from './routes/ai-ceo.approvals'
import { Route as AiCeoAutomationsRouteImport } from './routes/ai-ceo.automations'
import { Route as AiCeoCompanyBrainRouteImport } from './routes/ai-ceo.company-brain'
import { Route as AiCeoDecisionEngineRouteImport } from './routes/ai-ceo.decision-engine'
import { Route as AiCeoLearningRouteImport } from './routes/ai-ceo.learning'
import { Route as AiCeoLiveMonitorRouteImport } from './routes/ai-ceo.live-monitor'
import { Route as AiCeoPerformanceRouteImport } from './routes/ai-ceo.performance'
import { Route as AiCeoPredictionsRouteImport } from './routes/ai-ceo.predictions'
import { Route as AiCeoReportsRouteImport } from './routes/ai-ceo.reports'
import { Route as AiCeoResearchRouteImport } from './routes/ai-ceo.research'
import { Route as AiCeoRiskRouteImport } from './routes/ai-ceo.risk'
import { Route as AiCeoSettingsRouteImport } from './routes/ai-ceo.settings'
import { Route as AiCeoTasksRouteImport } from './routes/ai-ceo.tasks'
import { Route as ApiCeoBriefRouteImport } from './routes/api/ceo-brief'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiCeoRoute = AiCeoRouteImport.update({
  id: '/ai-ceo',
  path: '/ai-ceo',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRoute = OwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const SoftwarewalaRoute = SoftwarewalaRouteImport.update({
  id: '/softwarewala',
  path: '/softwarewala',
  getParentRoute: () => rootRouteImport,
} as any)
const AiCeoIndexRoute = AiCeoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AiCeoRoute,
} as any)
const AiCeoActivityRoute = AiCeoActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AiCeoRoute,
} as any)
const AiCeoAgentsRoute = AiCeoAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AiCeoRoute,
} as any)
const AiCeoApprovalsRoute = AiCeoApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AiCeoRoute,
} as any)
const AiCeoAutomationsRoute = AiCeoAutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => AiCeoRoute,
} as any)
const AiCeoCompanyBrainRoute = AiCeoCompanyBrainRouteImport.update({
  id: '/company-brain',
  path: '/company-brain',
  getParentRoute: () => AiCeoRoute,
} as any)
const AiCeoDecisionEngineRoute = AiCeoDecisionEngineRouteImport.update({
  id: '/decision-engine',
  path: '/decision-engine',
  getParentRoute: () => AiCeoRoute,
} as any)
const AiCeoLearningRoute = AiCeoLearningRouteImport.update({
  id: '/learning',
  path: '/learning',
  getParentRoute: () => AiCeoRoute,
} as any)
const AiCeoLiveMonitorRoute = AiCeoLiveMonitorRouteImport.update({
  id: '/live-monitor',
  path: '/live-monitor',
  getParentRoute: () => AiCeoRoute,
} as any)
const AiCeoPerformanceRoute = AiCeoPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => AiCeoRoute,
} as any)
const AiCeoPredictionsRoute = AiCeoPredictionsRouteImport.update({
  id: '/predictions',
  path: '/predictions',
  getParentRoute: () => AiCeoRoute,
} as any)
const AiCeoReportsRoute = AiCeoReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AiCeoRoute,
} as any)
const AiCeoResearchRoute = AiCeoResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => AiCeoRoute,
} as any)
const AiCeoRiskRoute = AiCeoRiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => AiCeoRoute,
} as any)
const AiCeoSettingsRoute = AiCeoSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AiCeoRoute,
} as any)
const AiCeoTasksRoute = AiCeoTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AiCeoRoute,
} as any)
const ApiCeoBriefRoute = ApiCeoBriefRouteImport.update({
  id: '/api/ceo-brief',
  path: '/api/ceo-brief',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-ceo': typeof AiCeoRouteWithChildren
  '/owner': typeof OwnerRoute
  '/softwarewala': typeof SoftwarewalaRoute
  '/ai-ceo/activity': typeof AiCeoActivityRoute
  '/ai-ceo/agents': typeof AiCeoAgentsRoute
  '/ai-ceo/approvals': typeof AiCeoApprovalsRoute
  '/ai-ceo/automations': typeof AiCeoAutomationsRoute
  '/ai-ceo/company-brain': typeof AiCeoCompanyBrainRoute
  '/ai-ceo/decision-engine': typeof AiCeoDecisionEngineRoute
  '/ai-ceo/learning': typeof AiCeoLearningRoute
  '/ai-ceo/live-monitor': typeof AiCeoLiveMonitorRoute
  '/ai-ceo/performance': typeof AiCeoPerformanceRoute
  '/ai-ceo/predictions': typeof AiCeoPredictionsRoute
  '/ai-ceo/reports': typeof AiCeoReportsRoute
  '/ai-ceo/research': typeof AiCeoResearchRoute
  '/ai-ceo/risk': typeof AiCeoRiskRoute
  '/ai-ceo/settings': typeof AiCeoSettingsRoute
  '/ai-ceo/tasks': typeof AiCeoTasksRoute
  '/api/ceo-brief': typeof ApiCeoBriefRoute
  '/ai-ceo/': typeof AiCeoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/owner': typeof OwnerRoute
  '/softwarewala': typeof SoftwarewalaRoute
  '/ai-ceo/activity': typeof AiCeoActivityRoute
  '/ai-ceo/agents': typeof AiCeoAgentsRoute
  '/ai-ceo/approvals': typeof AiCeoApprovalsRoute
  '/ai-ceo/automations': typeof AiCeoAutomationsRoute
  '/ai-ceo/company-brain': typeof AiCeoCompanyBrainRoute
  '/ai-ceo/decision-engine': typeof AiCeoDecisionEngineRoute
  '/ai-ceo/learning': typeof AiCeoLearningRoute
  '/ai-ceo/live-monitor': typeof AiCeoLiveMonitorRoute
  '/ai-ceo/performance': typeof AiCeoPerformanceRoute
  '/ai-ceo/predictions': typeof AiCeoPredictionsRoute
  '/ai-ceo/reports': typeof AiCeoReportsRoute
  '/ai-ceo/research': typeof AiCeoResearchRoute
  '/ai-ceo/risk': typeof AiCeoRiskRoute
  '/ai-ceo/settings': typeof AiCeoSettingsRoute
  '/ai-ceo/tasks': typeof AiCeoTasksRoute
  '/api/ceo-brief': typeof ApiCeoBriefRoute
  '/ai-ceo': typeof AiCeoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-ceo': typeof AiCeoRouteWithChildren
  '/owner': typeof OwnerRoute
  '/softwarewala': typeof SoftwarewalaRoute
  '/ai-ceo/activity': typeof AiCeoActivityRoute
  '/ai-ceo/agents': typeof AiCeoAgentsRoute
  '/ai-ceo/approvals': typeof AiCeoApprovalsRoute
  '/ai-ceo/automations': typeof AiCeoAutomationsRoute
  '/ai-ceo/company-brain': typeof AiCeoCompanyBrainRoute
  '/ai-ceo/decision-engine': typeof AiCeoDecisionEngineRoute
  '/ai-ceo/learning': typeof AiCeoLearningRoute
  '/ai-ceo/live-monitor': typeof AiCeoLiveMonitorRoute
  '/ai-ceo/performance': typeof AiCeoPerformanceRoute
  '/ai-ceo/predictions': typeof AiCeoPredictionsRoute
  '/ai-ceo/reports': typeof AiCeoReportsRoute
  '/ai-ceo/research': typeof AiCeoResearchRoute
  '/ai-ceo/risk': typeof AiCeoRiskRoute
  '/ai-ceo/settings': typeof AiCeoSettingsRoute
  '/ai-ceo/tasks': typeof AiCeoTasksRoute
  '/api/ceo-brief': typeof ApiCeoBriefRoute
  '/ai-ceo/': typeof AiCeoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-ceo'
    | '/owner'
    | '/softwarewala'
    | '/ai-ceo/activity'
    | '/ai-ceo/agents'
    | '/ai-ceo/approvals'
    | '/ai-ceo/automations'
    | '/ai-ceo/company-brain'
    | '/ai-ceo/decision-engine'
    | '/ai-ceo/learning'
    | '/ai-ceo/live-monitor'
    | '/ai-ceo/performance'
    | '/ai-ceo/predictions'
    | '/ai-ceo/reports'
    | '/ai-ceo/research'
    | '/ai-ceo/risk'
    | '/ai-ceo/settings'
    | '/ai-ceo/tasks'
    | '/api/ceo-brief'
    | '/ai-ceo/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/owner'
    | '/softwarewala'
    | '/ai-ceo/activity'
    | '/ai-ceo/agents'
    | '/ai-ceo/approvals'
    | '/ai-ceo/automations'
    | '/ai-ceo/company-brain'
    | '/ai-ceo/decision-engine'
    | '/ai-ceo/learning'
    | '/ai-ceo/live-monitor'
    | '/ai-ceo/performance'
    | '/ai-ceo/predictions'
    | '/ai-ceo/reports'
    | '/ai-ceo/research'
    | '/ai-ceo/risk'
    | '/ai-ceo/settings'
    | '/ai-ceo/tasks'
    | '/api/ceo-brief'
    | '/ai-ceo'
  id:
    | '__root__'
    | '/'
    | '/ai-ceo'
    | '/owner'
    | '/softwarewala'
    | '/ai-ceo/activity'
    | '/ai-ceo/agents'
    | '/ai-ceo/approvals'
    | '/ai-ceo/automations'
    | '/ai-ceo/company-brain'
    | '/ai-ceo/decision-engine'
    | '/ai-ceo/learning'
    | '/ai-ceo/live-monitor'
    | '/ai-ceo/performance'
    | '/ai-ceo/predictions'
    | '/ai-ceo/reports'
    | '/ai-ceo/research'
    | '/ai-ceo/risk'
    | '/ai-ceo/settings'
    | '/ai-ceo/tasks'
    | '/api/ceo-brief'
    | '/ai-ceo/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiCeoRoute: typeof AiCeoRouteWithChildren
  OwnerRoute: typeof OwnerRoute
  SoftwarewalaRoute: typeof SoftwarewalaRoute
  ApiCeoBriefRoute: typeof ApiCeoBriefRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-ceo': {
      id: '/ai-ceo'
      path: '/ai-ceo'
      fullPath: '/ai-ceo'
      preLoaderRoute: typeof AiCeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner': {
      id: '/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof OwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/softwarewala': {
      id: '/softwarewala'
      path: '/softwarewala'
      fullPath: '/softwarewala'
      preLoaderRoute: typeof SoftwarewalaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-ceo/': {
      id: '/ai-ceo/'
      path: '/'
      fullPath: '/ai-ceo/'
      preLoaderRoute: typeof AiCeoIndexRouteImport
      parentRoute: typeof AiCeoRoute
    }
    '/ai-ceo/activity': {
      id: '/ai-ceo/activity'
      path: '/activity'
      fullPath: '/ai-ceo/activity'
      preLoaderRoute: typeof AiCeoActivityRouteImport
      parentRoute: typeof AiCeoRoute
    }
    '/ai-ceo/agents': {
      id: '/ai-ceo/agents'
      path: '/agents'
      fullPath: '/ai-ceo/agents'
      preLoaderRoute: typeof AiCeoAgentsRouteImport
      parentRoute: typeof AiCeoRoute
    }
    '/ai-ceo/approvals': {
      id: '/ai-ceo/approvals'
      path: '/approvals'
      fullPath: '/ai-ceo/approvals'
      preLoaderRoute: typeof AiCeoApprovalsRouteImport
      parentRoute: typeof AiCeoRoute
    }
    '/ai-ceo/automations': {
      id: '/ai-ceo/automations'
      path: '/automations'
      fullPath: '/ai-ceo/automations'
      preLoaderRoute: typeof AiCeoAutomationsRouteImport
      parentRoute: typeof AiCeoRoute
    }
    '/ai-ceo/company-brain': {
      id: '/ai-ceo/company-brain'
      path: '/company-brain'
      fullPath: '/ai-ceo/company-brain'
      preLoaderRoute: typeof AiCeoCompanyBrainRouteImport
      parentRoute: typeof AiCeoRoute
    }
    '/ai-ceo/decision-engine': {
      id: '/ai-ceo/decision-engine'
      path: '/decision-engine'
      fullPath: '/ai-ceo/decision-engine'
      preLoaderRoute: typeof AiCeoDecisionEngineRouteImport
      parentRoute: typeof AiCeoRoute
    }
    '/ai-ceo/learning': {
      id: '/ai-ceo/learning'
      path: '/learning'
      fullPath: '/ai-ceo/learning'
      preLoaderRoute: typeof AiCeoLearningRouteImport
      parentRoute: typeof AiCeoRoute
    }
    '/ai-ceo/live-monitor': {
      id: '/ai-ceo/live-monitor'
      path: '/live-monitor'
      fullPath: '/ai-ceo/live-monitor'
      preLoaderRoute: typeof AiCeoLiveMonitorRouteImport
      parentRoute: typeof AiCeoRoute
    }
    '/ai-ceo/performance': {
      id: '/ai-ceo/performance'
      path: '/performance'
      fullPath: '/ai-ceo/performance'
      preLoaderRoute: typeof AiCeoPerformanceRouteImport
      parentRoute: typeof AiCeoRoute
    }
    '/ai-ceo/predictions': {
      id: '/ai-ceo/predictions'
      path: '/predictions'
      fullPath: '/ai-ceo/predictions'
      preLoaderRoute: typeof AiCeoPredictionsRouteImport
      parentRoute: typeof AiCeoRoute
    }
    '/ai-ceo/reports': {
      id: '/ai-ceo/reports'
      path: '/reports'
      fullPath: '/ai-ceo/reports'
      preLoaderRoute: typeof AiCeoReportsRouteImport
      parentRoute: typeof AiCeoRoute
    }
    '/ai-ceo/research': {
      id: '/ai-ceo/research'
      path: '/research'
      fullPath: '/ai-ceo/research'
      preLoaderRoute: typeof AiCeoResearchRouteImport
      parentRoute: typeof AiCeoRoute
    }
    '/ai-ceo/risk': {
      id: '/ai-ceo/risk'
      path: '/risk'
      fullPath: '/ai-ceo/risk'
      preLoaderRoute: typeof AiCeoRiskRouteImport
      parentRoute: typeof AiCeoRoute
    }
    '/ai-ceo/settings': {
      id: '/ai-ceo/settings'
      path: '/settings'
      fullPath: '/ai-ceo/settings'
      preLoaderRoute: typeof AiCeoSettingsRouteImport
      parentRoute: typeof AiCeoRoute
    }
    '/ai-ceo/tasks': {
      id: '/ai-ceo/tasks'
      path: '/tasks'
      fullPath: '/ai-ceo/tasks'
      preLoaderRoute: typeof AiCeoTasksRouteImport
      parentRoute: typeof AiCeoRoute
    }
    '/api/ceo-brief': {
      id: '/api/ceo-brief'
      path: '/api/ceo-brief'
      fullPath: '/api/ceo-brief'
      preLoaderRoute: typeof ApiCeoBriefRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AiCeoRouteChildren {
  AiCeoActivityRoute: typeof AiCeoActivityRoute
  AiCeoAgentsRoute: typeof AiCeoAgentsRoute
  AiCeoApprovalsRoute: typeof AiCeoApprovalsRoute
  AiCeoAutomationsRoute: typeof AiCeoAutomationsRoute
  AiCeoCompanyBrainRoute: typeof AiCeoCompanyBrainRoute
  AiCeoDecisionEngineRoute: typeof AiCeoDecisionEngineRoute
  AiCeoLearningRoute: typeof AiCeoLearningRoute
  AiCeoLiveMonitorRoute: typeof AiCeoLiveMonitorRoute
  AiCeoPerformanceRoute: typeof AiCeoPerformanceRoute
  AiCeoPredictionsRoute: typeof AiCeoPredictionsRoute
  AiCeoReportsRoute: typeof AiCeoReportsRoute
  AiCeoResearchRoute: typeof AiCeoResearchRoute
  AiCeoRiskRoute: typeof AiCeoRiskRoute
  AiCeoSettingsRoute: typeof AiCeoSettingsRoute
  AiCeoTasksRoute: typeof AiCeoTasksRoute
  AiCeoIndexRoute: typeof AiCeoIndexRoute
}

const AiCeoRouteChildren: AiCeoRouteChildren = {
  AiCeoActivityRoute: AiCeoActivityRoute,
  AiCeoAgentsRoute: AiCeoAgentsRoute,
  AiCeoApprovalsRoute: AiCeoApprovalsRoute,
  AiCeoAutomationsRoute: AiCeoAutomationsRoute,
  AiCeoCompanyBrainRoute: AiCeoCompanyBrainRoute,
  AiCeoDecisionEngineRoute: AiCeoDecisionEngineRoute,
  AiCeoLearningRoute: AiCeoLearningRoute,
  AiCeoLiveMonitorRoute: AiCeoLiveMonitorRoute,
  AiCeoPerformanceRoute: AiCeoPerformanceRoute,
  AiCeoPredictionsRoute: AiCeoPredictionsRoute,
  AiCeoReportsRoute: AiCeoReportsRoute,
  AiCeoResearchRoute: AiCeoResearchRoute,
  AiCeoRiskRoute: AiCeoRiskRoute,
  AiCeoSettingsRoute: AiCeoSettingsRoute,
  AiCeoTasksRoute: AiCeoTasksRoute,
  AiCeoIndexRoute: AiCeoIndexRoute,
}

const AiCeoRouteWithChildren = AiCeoRoute._addFileChildren(AiCeoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiCeoRoute: AiCeoRouteWithChildren,
  OwnerRoute: OwnerRoute,
  SoftwarewalaRoute: SoftwarewalaRoute,
  ApiCeoBriefRoute: ApiCeoBriefRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
